name = "coolguy-site"
type = "javascript"

[site]
bucket = "./public"  # Where personal website files are stored

[build]
command = "echo 'No build step needed'"

[dev]
port = 8787

[vars]
DISCORD_CDN = "https://cdn.discordapp.com/attachments/"
